[Eth]
NetworkId = 6660001
SyncMode = "full"
TrieTimeout = 1200000000000
RPCGasCap = 40000000

[Eth.Miner]
GasFloor = 40000000
GasCeil =  40000000
GasPrice = 0
Recommit = 3000000000
Noverify = false

[Eth.GPO]
Blocks = 6
Percentile = 10

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1
PriceBump = 10
AccountSlots = 2000
GlobalSlots = 10000
AccountQueue = 60
GlobalQueue = 1000
Lifetime = 10800000000000

[Node]
DataDir = "/root/.ethereum"
InsecureUnlockAllowed = true
NoUSB = true
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPCors = ["*"]
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "web3", "net", "admin", "debug","personal", "miner", "chaos", "debug"]
WSHost = ""
WSPort = 8546
WSModules = ["net", "web3", "eth"]
GraphQLVirtualHosts = ["localhost"]

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
TrustedNodes = []
ListenAddr = ":30303"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 3000000000
WriteTimeout = 5000000000
IdleTimeout = 120000000000
